# Generated by Django 3.2.15 on 2022-12-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True),
        ),
    ]
