# Generated by Django 3.2.15 on 2022-12-16 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20221216_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag_name',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 10, 33, 111802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 10, 33, 111856, tzinfo=utc)),
        ),
    ]
