# Generated by Django 3.2.15 on 2022-12-16 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20221216_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 24, 9, 916813, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 24, 9, 916868, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='featureimage',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
    ]
