# Generated by Django 3.2.15 on 2022-12-16 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20221216_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_name',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 47, 47, 288885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 6, 47, 47, 288940, tzinfo=utc)),
        ),
    ]
