# Generated by Django 3.2.15 on 2022-12-16 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20221216_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 12, 22, 34, 993259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 12, 22, 34, 993317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
    ]
