# Generated by Django 3.2.15 on 2022-12-17 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20221217_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 9, 22, 19, 662259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 9, 22, 19, 662324, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 9, 22, 19, 663535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 9, 22, 19, 663627, tzinfo=utc)),
        ),
    ]
