# Generated by Django 3.2.15 on 2022-12-21 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 5, 15, 15, 466795, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 5, 15, 15, 466126, tzinfo=utc)),
        ),
    ]
