# Generated by Django 3.2.15 on 2022-12-26 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20221221_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 9, 3, 5, 900098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 26, 9, 3, 5, 899425, tzinfo=utc)),
        ),
    ]
